const DEFAULT_DATA = {
  attendance: { total: 250, authors: 25, admin: 4 },
  ticketPrice: 0,

  expenses: [
    { id:'lunch', label:'Lunch', type:'perunit', unitPrice:15.00, qty:250, unitLabel:'per person',
      tip:{enabled:true,type:'fixed',pct:15,fixedAmt:562.50}, spent:0, notes:'', expanded:false },
    { id:'venue', label:'Venue', type:'fixed', fixedAmt:1615.00, spent:0, notes:'Contact venue re: setup time', expanded:false },
    { id:'author_gifts', label:'Gifts for authors', type:'perunit', unitPrice:1.40, qty:25, unitLabel:'per author', spent:0, notes:'', expanded:false },
    { id:'photographer', label:'Photographer', type:'fixed', fixedAmt:450.00,
      tip:{enabled:true,type:'fixed',pct:15,fixedAmt:50.00}, spent:0, notes:'', expanded:false },
    { id:'hats', label:'Hats', type:'subtable', subtable:'hats', spent:0, notes:'', expanded:false },
    { id:'totes', label:'Tote bags', type:'subtable', subtable:'totes', spent:0, notes:'', expanded:false },
    { id:'tshirts', label:'T-shirts', type:'subtable', subtable:'tshirts', spent:0, notes:'', expanded:false },
    { id:'prizes', label:'Prizes (BINGO)', type:'subtable', subtable:'prizes', spent:0, notes:'See prize manager', expanded:false },
    { id:'raffle', label:'Raffle prizes', type:'fixed', fixedAmt:600.00, spent:0, notes:'', expanded:false },
    { id:'swag', label:'Swag bag stuff', type:'subtable', subtable:'swag', spent:0, notes:'', expanded:false },
    { id:'decorations', label:'Decorations', type:'subtable', subtable:'decorations', spent:0, notes:'', expanded:false },
    { id:'misc', label:'Misc', type:'subtable', subtable:'misc', spent:0, notes:'', expanded:false },
    { id:'dinner', label:'Dinner with authors', type:'perunit', unitPrice:40.00, qty:25, unitLabel:'per author', spent:0, notes:'', expanded:false },
    { id:'cc_fee', label:'CC processing fee', type:'perunit', unitPrice:2.24, qty:221, unitLabel:'per ticket', spent:0, notes:'~3.2% per ticket', expanded:false },
    { id:'pay_selves', label:'Pay ourselves', type:'fixed', fixedAmt:500.00, spent:0, notes:'', expanded:false },
  ],

  // Which merch type is active this year
  merchType: 'hats', // 'hats' or 'tshirts'

  tshirts: [
    {label:'S',    size:'S',    price:8.00,  qty:10, desc:''},
    {label:'M',    size:'M',    price:8.00,  qty:79, desc:''},
    {label:'L',    size:'L',    price:8.00,  qty:71, desc:''},
    {label:'XL',   size:'XL',   price:8.00,  qty:48, desc:''},
    {label:'XXL',  size:'XXL',  price:9.50,  qty:28, desc:''},
    {label:'XXXL', size:'XXXL', price:11.00, qty:15, desc:''},
  ],
  hats: [
    {label:'Two color (2.25×4")', price:5.55, qty:250, notes:'Current choice'},
  ],
  totes: [
    {label:'Standard (one color)', price:4.52, qty:250, notes:''},
  ],
  prizes: [
    {label:'BINGO prizes budget', est:2000.00, spent:0, notes:'See prize manager', url:''},
  ],
  swag: [
    {label:'Gracie Ruth Mitchell swag (×25)', est:50.00, spent:0, notes:'', url:''},
    {label:'Stickers (300, 2 per person)',    est:10.43, spent:0, notes:'', url:''},
    {label:'Soirée stickers (191)',           est:48.00, spent:0, notes:'', url:''},
  ],
  decorations: [
    {label:'Table runners',        est:40.00, spent:0, notes:'Need to make new ones', url:''},
    {label:'Centerpieces (Lesli)', est:0.00,  spent:0, notes:'Pick up from Lesli',    url:''},
    {label:'Candles',              est:30.00, spent:0, notes:'',                       url:''},
    {label:'Paper flowers + pins', est:0.00,  spent:0, notes:'Already have',           url:''},
    {label:'Book starbursts',      est:0.00,  spent:0, notes:'Already have',           url:''},
    {label:'Linens (ALSCO)',       est:60.00, spent:0, notes:'40 @ $1.50',             url:''},
  ],
  misc: [
    {label:'Chapstick labels',             est:25,  spent:0, notes:'2.125"×1.6875" OL421', url:''},
    {label:'BINGO cards',                  est:25,  spent:0, notes:'',                      url:'https://myfreebingocards.com'},
    {label:'Print BINGO at Staples (260)', est:100, spent:0, notes:'$.72/sheet own paper',  url:''},
    {label:'Cardstock for BINGO',          est:20,  spent:0, notes:'',                      url:''},
    {label:'Chapstick supplies',           est:120, spent:0, notes:'',                      url:''},
    {label:'Costco water bottles',         est:15,  spent:0, notes:'40 × $3.99',            url:''},
    {label:'Water bottle labels',          est:10,  spent:0, notes:'OL435LP',               url:'https://www.onlinelabels.com/products/ol435lp'},
    {label:'Name tags',                    est:205, spent:0, notes:'Avery 74459',           url:''},
    {label:'Raffle boxes',                 est:15,  spent:0, notes:'',                      url:'https://a.co/d/2rTdUDV'},
  ],

  todos: [
    {id:1,  who:'Nicole',     task:'Authors: Collect multi-author story',                  done:false},
    {id:2,  who:'Heather',    task:'Authors: Get QR barcode for all their SM stuff',        done:false},
    {id:3,  who:'Heather',    task:'Authors: Make QR barcode sheet for all authors',        done:false},
    {id:4,  who:'Nicole',     task:'Authors: Name plates for Q&A sessions',                 done:false},
    {id:5,  who:'Nicole',     task:'Authors: Pick Q&A questions',                           done:false},
    {id:6,  who:'Alyssa',     task:'Authors: Thank You notes',                              done:false},
    {id:7,  who:'',           task:'Decor: Make new runners',                               done:false},
    {id:8,  who:'Nicole',     task:'Decor: Stain new centerpieces',                         done:false},
    {id:9,  who:'Nicole',     task:'Donations: Make THANK YOU tags and bookmarks',          done:false},
    {id:10, who:'',           task:'Get a tote big enough for table runners',               done:false},
    {id:11, who:'',           task:'Get enough prizes',                                     done:false},
    {id:12, who:'',           task:'Hats: Design them',                                     done:false},
    {id:13, who:'Nicole',     task:'Hats: Order them',                                      done:false},
    {id:14, who:'Alyssa',     task:'Inventory everything at Alyssa\'s house',               done:false},
    {id:15, who:'Nicole',     task:'Inventory everything at Nicole\'s house',               done:false},
    {id:16, who:'Nicole',     task:'Linens: Call and arrange (40 @ $1.50)',                 done:false},
    {id:17, who:'',           task:'Name tags: Design them',                                done:false},
    {id:18, who:'Nicole',     task:'Name tags: Order them',                                 done:false},
    {id:19, who:'Jordan',     task:'Name tags: QR code & profile from Insta account',       done:false},
    {id:20, who:'',           task:'Package prizes',                                        done:false},
    {id:21, who:'Nicole',     task:'Pick up centerpieces from Lesli',                       done:false},
    {id:22, who:'Nicole',     task:'Print multi-author story and get in binder',            done:false},
    {id:23, who:'',           task:'Print: Chapstick labels',                               done:false},
    {id:24, who:'',           task:'Print: Name tags',                                      done:false},
    {id:25, who:'',           task:'Print: Tote games',                                     done:false},
    {id:26, who:'Nicole',     task:'Print: Water bottle labels',                            done:false},
    {id:27, who:'Nicole',     task:'Prizes: Call Covenant — Shara Meredith',               done:false},
    {id:28, who:'Lynette',    task:'Prizes: Make sure we have enough',                     done:false},
    {id:29, who:'Nicole',     task:'Put together PowerPoint presentation',                  done:false},
    {id:30, who:'Nicole',     task:'Raffle: Boxes for drawings',                            done:false},
    {id:31, who:'Nicole',     task:'Raffle: Signs on raffle drawing boxes',                 done:false},
    {id:32, who:'',           task:'Stuff totes',                                           done:false},
    {id:33, who:'Nicole',     task:'SWAG: Inventory at Nicole\'s house',                    done:false},
    {id:34, who:'Alyssa',     task:'SWAG: Inventory from Alyssa\'s house',                 done:false},
    {id:35, who:'',           task:'Tote: Bracelets for everyone',                          done:false},
    {id:36, who:'',           task:'Tote: Make bookish games',                              done:false},
    {id:37, who:'Lynette',    task:'Tote: Make flyer with book businesses',                done:false},
    {id:38, who:'Lynette',    task:'Tote: Thanks to businesses who donated',               done:false},
    {id:39, who:'Jess',       task:'Totes: Design them',                                   done:false},
    {id:40, who:'Nicole',     task:'Totes: Order them',                                    done:false},
    {id:41, who:'Nicole',     task:'Venue: Schedule ballroom',                              done:false},
    {id:42, who:'',           task:'Water bottles: Buy them',                               done:false},
    {id:43, who:'Nicole',     task:'Water bottles: Order labels',                           done:false},
    {id:44, who:'',           task:'Water bottles: Put on labels',                          done:false},
  ],

  inventory: [
    {id:1,  loc:"Alyssa's", cat:'Backdrops', item:'Backdrops: Curtain backdrop',            note:'', packed:false},
    {id:2,  loc:"Alyssa's", cat:'Backdrops', item:'Backdrops: Curtain backdrop curtains',   note:'', packed:false},
    {id:3,  loc:"Alyssa's", cat:'Backdrops', item:'Backdrops: Curtain backdrop supports',   note:'', packed:false},
    {id:4,  loc:"Alyssa's", cat:'Backdrops', item:'Backdrops: Tri-fold book page backdrop', note:'', packed:false},
    {id:5,  loc:"Alyssa's", cat:'Misc', item:'Bible',                                  note:'', packed:false},
    {id:6,  loc:"Alyssa's", cat:'Decor', item:'Decor: Vases (2 boxes)',                 note:'', packed:false},
    {id:7,  loc:"Alyssa's", item:"Misc: Alyssa's book exchange book",      note:'', packed:false},
    {id:8,  loc:"Alyssa's", cat:'Prize table', item:'Prizes: Platforms/shelves for prizes',   note:'', packed:false},
    {id:9,  loc:"Nicole's", cat:'Backdrops', item:'Backdrops: Book exchange bookshelf',      note:'', packed:false},
    {id:10, loc:"Nicole's", cat:'Backdrops', item:'Backdrops: Bookshelf pins and brackets',  note:'', packed:false},
    {id:11, loc:"Nicole's", cat:'Backdrops', item:'Backdrops: Bookshelf shelves (4)',        note:'', packed:false},
    {id:12, loc:"Nicole's", cat:'Check-in', item:'Check-in bag with polls',                note:'Garage — bag',        packed:false},
    {id:13, loc:"Nicole's", cat:'Check-in', item:'Check-in bins (4)',                       note:'Garage — black tote', packed:false},
    {id:14, loc:"Nicole's", cat:'Decor', item:'Decor: Bin with paper flowers + pins',   note:'Garage — silver tote',packed:false},
    {id:15, loc:"Nicole's", cat:'Decor', item:'Decor: Book page banners',               note:'', packed:false},
    {id:16, loc:"Nicole's", cat:'Decor', item:'Decor: Book starbursts',                 note:'', packed:false},
    {id:17, loc:"Nicole's", cat:'Decor', item:'Decor: Face cutout stands + screws (8)', note:'Garage — cubby',      packed:false},
    {id:18, loc:"Nicole's", cat:'Decor', item:'Decor: Face cutouts (4)',                note:'Garage — cubby',      packed:false},
    {id:19, loc:"Nicole's", cat:'Decor', item:'Decor: Welcome easel',                   note:'Garage — cubby',      packed:false},
    {id:20, loc:"Nicole's", cat:'Misc', item:'Extra canvas totes from last year (4)',   note:'Garage — black tote', packed:false},
    {id:21, loc:"Nicole's", cat:'Misc', item:'Misc: My laptop',                        note:'', packed:false},
    {id:22, loc:"Nicole's", item:"Misc: Nicole's book exchange book",      note:'', packed:false},
    {id:23, loc:"Nicole's", cat:'Check-in', item:'Name tags',                              note:'Design Center',       packed:false},
    {id:24, loc:"Nicole's", cat:'Prize table', item:'Raffle tickets',                         note:'Garage — black tote', packed:false},
    {id:25, loc:"Nicole's", cat:'Misc', item:'Water bottle labels',                    note:'Design center',       packed:false},
    {id:26, loc:'Other',    cat:'Decor', item:'Decor: Candles',                         note:'', packed:false},
    {id:27, loc:'Other',    cat:'Decor', item:'Decor: Centerpiece stuff from Lesli',    note:'', packed:false},
    {id:28, loc:'Other',    cat:'Misc', item:'Friendship bracelet stuff',              note:'', packed:false},
    {id:29, loc:'Other',    cat:'Misc', item:'Misc: Device for playing music',         note:'', packed:false},
    {id:30, loc:'Other',    cat:'Misc', item:'Misc: Drill with bits',                  note:'', packed:false},
    {id:31, loc:'Other',    cat:'Misc', item:'Sign to purchase bead boards (1)',       note:'', packed:false},
    {id:32, loc:'Other',    cat:'Misc', item:'Sign with bead board instructions (12)', note:'', packed:false},
  ],

  // Custom locations saved by user
  customLocations: [],

  authors: [
    {id:'a1', name:'Jessica Scarlett',  status:'Confirmed', role:'Book Signing', infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'', website:'', _expanded:false},
    {id:'a2', name:'Aspen Hadley',      status:'Confirmed', role:'Book Signing', infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'', website:'', _expanded:false},
    {id:'a3', name:'Jentry Flint',      status:'Confirmed', role:'Book Signing', infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'', website:'', _expanded:false},
    {id:'a4', name:'Amanda P Jones',    status:'Confirmed', role:'Book Signing', infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'', website:'', _expanded:false},
    {id:'a5', name:'Sarah M Eden',      status:'Asked',     role:'Book Signing', infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'', website:'', _expanded:false},
    {id:'a6', name:'Shannon Castelton', status:'Maybe',     role:'Q&A',          infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false, notes:'If health is good', website:'', _expanded:false},
  ],

  wishlist: [
    {name:'Traci Abramson',       note:''},
    {name:'Courtney Walsh',       note:'Popular in her genre'},
    {name:'Nancy Allan Campbell', note:'Love her'},
    {name:'Deborah Hathaway',     note:''},
    {name:'Anneka Walker',        note:''},
    {name:'Tiffany Odekirk',      note:'Want to ask her'},
    {name:'Shannon Castleton',    note:'2027 goal!'},
    {name:'Samantha Hastings',    note:'Contacted us on Insta'},
    {name:'Marion de Ray',        note:'Contacted us on Insta'},
  ],

  people: ['Nicole','Alyssa','Lynette','Heather','Jordan','Jess','Kyle Kimzey'],
  peopleGroups: {
    'Admin':   ['Nicole','Alyssa','Lynette','Kyle Kimzey'],
    'Set-up':  ['Jordan','Heather'],
    'Misc':    ['Jess'],
  },

  nextId: 200,
  eventName: 'Bookish Summer Soirée 2027',
  eventYear: '2027',
};
