// data.js — DEFAULT DATA for Bookish Summer Soirée 2027
const DEFAULT_DATA = {
  attendance: { total: 175, authors: 18, admin: 4 },
  ticketPrice: 75,
  ccFeePercent: 3.2,
  nextId: 200,
  eventName: 'Bookish Summer Soirée 2027',
  eventYear: '2027',
  merchType: 'hats',
  merchOptions: ['hats','tshirts'],
  merchLabels: { hats:'Hats', tshirts:'T-shirts' },
  peopleGroups: {
    'Admin':    ['Nicole','Alyssa','Lynette','Kyle Kimzey'],
    'Set-up':   ['Jordan','Heather'],
    'Misc':     ['Jess'],
  },
  peopleContacts: {},
  customLocations: [],
  inventoryCategories: ['Backdrops','Check-in','Decor','Misc','Prize table'],
  todoCategories: ['Authors','Decor','Donations','Inventory','Merch','Name Tags','Print','Prizes','Raffle','SWAG','Totes','Venue','Water Bottles'],

  expenses: [
    { id:'cc_fee',      label:'CC processing fee',  type:'cc_fee',   ccPct:3.2,     spent:0, notes:'3.2% per ticket', expanded:false },
    { id:'venue',       label:'Venue',              type:'fixed',    fixedAmt:1615, spent:0, notes:'Contact venue re: setup time', expanded:false },
    { id:'lunch',       label:'Lunch / Food',       type:'perunit',  unitPrice:15,  unitLabelType:'total', qty:175, unitLabel:'per person', spent:0, notes:'', tip:{enabled:true,type:'fixed',fixedAmt:562.50}, expanded:false },
    { id:'prizes_budget',label:'Prizes (BINGO)',     type:'fixed',    fixedAmt:2000, spent:328.73, notes:'Tracked in Prize Manager', expanded:false },
    { id:'raffle',      label:'Raffle prizes',      type:'fixed',    fixedAmt:600,  spent:0, notes:'', expanded:false },
    { id:'hats',        label:'Hats (Merch)',       type:'subtable', subtable:'hats',        spent:0, notes:'', expanded:false },
    { id:'tshirts',     label:'T-shirts (Merch)',   type:'subtable', subtable:'tshirts',     spent:0, notes:'', expanded:false },
    { id:'totes',       label:'Tote bags',          type:'subtable', subtable:'totes',       spent:0, notes:'', expanded:false },
    { id:'decorations', label:'Decorations',        type:'subtable', subtable:'decorations', spent:0, notes:'', expanded:false },
    { id:'misc',        label:'Misc',               type:'subtable', subtable:'misc',        spent:0, notes:'', expanded:false },
    { id:'swag',        label:'Swag bag stuff',     type:'subtable', subtable:'swag',        spent:0, notes:'', expanded:false },
    { id:'photographer',label:'Photographer',       type:'fixed',    fixedAmt:450,  spent:0, notes:'', tip:{enabled:true,type:'fixed',fixedAmt:50}, expanded:false },
    { id:'dinner',      label:'Author dinner',      type:'perunit',  unitPrice:40,  unitLabelType:'authors', qty:18, unitLabel:'per author', spent:0, notes:'', expanded:false },
    { id:'author_gifts',label:'Author gifts',       type:'perunit',  unitPrice:1.40,unitLabelType:'authors', qty:18, unitLabel:'per author', spent:0, notes:'', expanded:false },
    { id:'admin_pay',   label:'Admin',              type:'fixed',    fixedAmt:500,  spent:0, notes:'', expanded:false },
  ],

  tshirts: [
    {label:'S',    price:8.00,  qty:10,  notes:''},
    {label:'M',    price:8.00,  qty:79,  notes:''},
    {label:'L',    price:8.00,  qty:71,  notes:''},
    {label:'XL',   price:8.00,  qty:48,  notes:''},
    {label:'XXL',  price:9.50,  qty:28,  notes:''},
    {label:'XXXL', price:11.00, qty:15,  notes:''},
  ],
  hats: [
    {label:'Two color (2.25x4")', price:5.55, qty:175, notes:'Current choice'},
  ],
  totes: [
    {label:'Standard (one color)', price:4.52, qty:175, notes:''},
  ],
  prizes: [],
  swag: [
    {label:'Gracie Ruth Mitchell swag', est:50,    spent:0,  notes:'x25', url:''},
    {label:'Stickers (300)',            est:10.43, spent:10.43, notes:'2 per person', url:''},
    {label:'Soiree stickers (191)',     est:48,    spent:48, notes:'', url:''},
  ],
  decorations: [
    {label:'Table runners',        est:40,  spent:0, notes:'Need to make new ones', url:''},
    {label:'Centerpieces',         est:0,   spent:0, notes:'Pick up from Lesli',    url:''},
    {label:'Candles',              est:30,  spent:0, notes:'',                      url:''},
    {label:'Paper flowers + pins', est:0,   spent:0, notes:'Already have',          url:''},
    {label:'Book starbursts',      est:0,   spent:0, notes:'Already have',          url:''},
    {label:'Linens (ALSCO)',       est:60,  spent:0, notes:'40 @ $1.50',            url:''},
  ],
  misc: [
    {label:'Chapstick labels',             est:25,  spent:30.83, notes:'2.125x1.6875 OL421', url:''},
    {label:'Soiree sticker labels',        est:65,  spent:20.40, notes:'Sticker labels',     url:''},
    {label:'Raffle boxes',                 est:15,  spent:10.66, notes:'',                   url:'https://a.co/d/2rTdUDV'},
    {label:'Chapstick labels print',       est:25,  spent:20.94, notes:'2.125x1.6875',       url:''},
    {label:'BINGO cards',                  est:25,  spent:20,    notes:'',                   url:'https://myfreebingocards.com'},
    {label:'Print BINGO at Staples',       est:100, spent:93.60, notes:'$.72/sheet',         url:''},
    {label:'Cardstock for BINGO',          est:20,  spent:15,    notes:'',                   url:''},
    {label:'Chapstick supplies',           est:120, spent:120,   notes:'',                   url:''},
    {label:'Costco water bottles',         est:15,  spent:10,    notes:'40 x $3.99',         url:''},
    {label:'Water bottle labels',          est:10,  spent:0,     notes:'OL435LP',            url:''},
    {label:'Pencils',                      est:0,   spent:0,     notes:'Already have',       url:''},
    {label:'Name tags',                    est:205, spent:205,   notes:'Avery 74459',        url:''},
  ],

  todos: [
    {id:1,  who:'Nicole',  cat:'Authors',       task:'Collect multi-author story',                 notes:'', done:false},
    {id:2,  who:'Heather', cat:'Authors',       task:'Get QR barcode for all their SM stuff',      notes:'', done:false},
    {id:3,  who:'Heather', cat:'Authors',       task:'Make QR barcode sheet for all authors',      notes:'', done:false},
    {id:4,  who:'Nicole',  cat:'Authors',       task:'Name plates for Q&A sessions',               notes:'', done:false},
    {id:5,  who:'Nicole',  cat:'Authors',       task:'Pick Q&A questions',                         notes:'', done:false},
    {id:6,  who:'Alyssa',  cat:'Authors',       task:'Thank You notes for authors',                notes:'', done:false},
    {id:7,  who:'',        cat:'Decor',         task:'Make new table runners',                     notes:'', done:false},
    {id:8,  who:'Nicole',  cat:'Decor',         task:'Stain new centerpieces',                     notes:'', done:false},
    {id:9,  who:'Nicole',  cat:'Donations',     task:'Make THANK YOU tags and bookmarks',          notes:'', done:false},
    {id:10, who:'',        cat:'Totes',         task:'Get a tote big enough for table runners',    notes:'', done:false},
    {id:11, who:'',        cat:'Prizes',        task:'Get enough prizes',                          notes:'', done:false},
    {id:12, who:'',        cat:'Merch',         task:'Design hats',                                notes:'', done:false},
    {id:13, who:'Nicole',  cat:'Merch',         task:'Order hats',                                 notes:'', done:false},
    {id:14, who:'Alyssa',  cat:'Inventory',     task:"Inventory everything at Alyssa's house",     notes:'', done:false},
    {id:15, who:'Nicole',  cat:'Inventory',     task:"Inventory everything at Nicole's house",     notes:'', done:false},
    {id:16, who:'Nicole',  cat:'Venue',         task:'Linens: call and arrange (40 @ $1.50)',      notes:'', done:false},
    {id:17, who:'',        cat:'Name Tags',     task:'Design name tags',                           notes:'', done:false},
    {id:18, who:'Nicole',  cat:'Name Tags',     task:'Order name tags',                            notes:'', done:false},
    {id:19, who:'Jordan',  cat:'Name Tags',     task:'QR code and profile from Insta account',     notes:'', done:false},
    {id:20, who:'',        cat:'Prizes',        task:'Package prizes',                             notes:'', done:false},
    {id:21, who:'Nicole',  cat:'Decor',         task:'Pick up centerpieces from Lesli',            notes:'', done:false},
    {id:22, who:'Nicole',  cat:'Authors',       task:'Print multi-author story and get in binder', notes:'', done:false},
    {id:23, who:'',        cat:'Print',         task:'Print chapstick labels',                     notes:'', done:false},
    {id:24, who:'',        cat:'Print',         task:'Print name tags',                            notes:'', done:false},
    {id:25, who:'',        cat:'Print',         task:'Print tote games',                           notes:'', done:false},
    {id:26, who:'Nicole',  cat:'Print',         task:'Print water bottle labels',                  notes:'', done:false},
    {id:27, who:'Nicole',  cat:'Prizes',        task:'Call Covenant - Shara Meredith',             notes:'', done:false},
    {id:28, who:'Lynette', cat:'Prizes',        task:'Make sure we have enough prizes',            notes:'', done:false},
    {id:29, who:'Nicole',  cat:'',              task:'Put together PowerPoint presentation',       notes:'', done:false},
    {id:30, who:'Nicole',  cat:'Raffle',        task:'Boxes for drawings',                         notes:'', done:false},
    {id:31, who:'Nicole',  cat:'Raffle',        task:'Signs on raffle drawing boxes',              notes:'', done:false},
    {id:32, who:'',        cat:'Totes',         task:'Stuff totes',                                notes:'', done:false},
    {id:33, who:'Nicole',  cat:'SWAG',          task:"Inventory SWAG at Nicole's house",           notes:'', done:false},
    {id:34, who:'Alyssa',  cat:'SWAG',          task:"Inventory SWAG from Alyssa's house",         notes:'', done:false},
    {id:35, who:'',        cat:'Totes',         task:'Bracelets for everyone',                     notes:'', done:false},
    {id:36, who:'',        cat:'Totes',         task:'Make bookish tote games',                    notes:'', done:false},
    {id:37, who:'Lynette', cat:'Totes',         task:'Make flyer with book businesses',            notes:'', done:false},
    {id:38, who:'Lynette', cat:'Totes',         task:'Thanks to businesses who donated',           notes:'', done:false},
    {id:39, who:'Jess',    cat:'Totes',         task:'Design totes',                               notes:'', done:false},
    {id:40, who:'Nicole',  cat:'Totes',         task:'Order totes',                                notes:'', done:false},
    {id:41, who:'Nicole',  cat:'Venue',         task:'Schedule ballroom',                          notes:'', done:false},
    {id:42, who:'',        cat:'Water Bottles', task:'Buy water bottles',                          notes:'', done:false},
    {id:43, who:'Nicole',  cat:'Water Bottles', task:'Order water bottle labels',                  notes:'', done:false},
    {id:44, who:'',        cat:'Water Bottles', task:'Put on water bottle labels',                 notes:'', done:false},
  ],

  inventory: [
    {id:1,  cat:'Backdrops',   loc:"Alyssa's", item:'Curtain backdrop',              note:'', packed:false},
    {id:2,  cat:'Backdrops',   loc:"Alyssa's", item:'Curtain backdrop curtains',     note:'', packed:false},
    {id:3,  cat:'Backdrops',   loc:"Alyssa's", item:'Curtain backdrop supports',     note:'', packed:false},
    {id:4,  cat:'Backdrops',   loc:"Alyssa's", item:'Tri-fold book page backdrop',   note:'', packed:false},
    {id:5,  cat:'Misc',        loc:"Alyssa's", item:'Bible',                         note:'', packed:false},
    {id:6,  cat:'Decor',       loc:"Alyssa's", item:'Vases (2 boxes)',               note:'', packed:false},
    {id:7,  cat:'Misc',        loc:"Alyssa's", item:"Alyssa's book exchange book",   note:'', packed:false},
    {id:8,  cat:'Prize table', loc:"Alyssa's", item:'Platforms/shelves for prizes',  note:'', packed:false},
    {id:9,  cat:'Backdrops',   loc:"Nicole's", item:'Book exchange bookshelf',       note:'', packed:false},
    {id:10, cat:'Backdrops',   loc:"Nicole's", item:'Bookshelf pins and brackets',   note:'', packed:false},
    {id:11, cat:'Backdrops',   loc:"Nicole's", item:'Bookshelf shelves (4)',         note:'', packed:false},
    {id:12, cat:'Check-in',    loc:"Nicole's", item:'Check-in bag with polls',       note:'Garage - bag',        packed:false},
    {id:13, cat:'Check-in',    loc:"Nicole's", item:'Check-in bins (4)',             note:'Garage - black tote', packed:false},
    {id:14, cat:'Decor',       loc:"Nicole's", item:'Bin with paper flowers + pins', note:'Garage - silver tote',packed:false},
    {id:15, cat:'Decor',       loc:"Nicole's", item:'Book page banners',             note:'', packed:false},
    {id:16, cat:'Decor',       loc:"Nicole's", item:'Book starbursts',               note:'', packed:false},
    {id:17, cat:'Decor',       loc:"Nicole's", item:'Face cutout stands + screws (8)',note:'Garage - cubby',     packed:false},
    {id:18, cat:'Decor',       loc:"Nicole's", item:'Face cutouts (4)',              note:'Garage - cubby',      packed:false},
    {id:19, cat:'Decor',       loc:"Nicole's", item:'Welcome easel',                 note:'Garage - cubby',      packed:false},
    {id:20, cat:'Misc',        loc:"Nicole's", item:'Extra canvas totes (4)',        note:'Garage - black tote', packed:false},
    {id:21, cat:'Misc',        loc:"Nicole's", item:'Laptop',                        note:'', packed:false},
    {id:22, cat:'Misc',        loc:"Nicole's", item:"Nicole's book exchange book",   note:'', packed:false},
    {id:23, cat:'Check-in',    loc:"Nicole's", item:'Name tags',                     note:'Design Center',       packed:false},
    {id:24, cat:'Prize table', loc:"Nicole's", item:'Raffle tickets',                note:'Garage - black tote', packed:false},
    {id:25, cat:'Misc',        loc:"Nicole's", item:'Water bottle labels',           note:'Design center',       packed:false},
    {id:26, cat:'Decor',       loc:'Other',    item:'Candles',                       note:'', packed:false},
    {id:27, cat:'Decor',       loc:'Other',    item:'Centerpiece stuff from Lesli',  note:'', packed:false},
    {id:28, cat:'Misc',        loc:'Other',    item:'Friendship bracelet stuff',     note:'', packed:false},
    {id:29, cat:'Misc',        loc:'Other',    item:'Device for playing music',      note:'', packed:false},
    {id:30, cat:'Misc',        loc:'Other',    item:'Drill with bits',               note:'', packed:false},
    {id:31, cat:'Prize table', loc:'Other',    item:'Sign to purchase bead boards',  note:'(1)', packed:false},
    {id:32, cat:'Prize table', loc:'Other',    item:'Sign with bead board instructions',note:'(12)', packed:false},
  ],

  authors: [
    {id:'a1',  name:'Amanda P Jones',      status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a2',  name:'Aspen Hadley',        status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a3',  name:'Jentry Flint',        status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a4',  name:'Jessica Scarlett',    status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a5',  name:'Kate Watson',         status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a6',  name:'Nicole J Kimzey',     status:'Confirmed', role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a7',  name:'Sarah M Eden',        status:'Asked',     role:'Book Signing', notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a8',  name:'Nancy Allan Campbell',status:'Confirmed', role:'Q&A',          notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a9',  name:'Shannon Castelton',   status:'Maybe',     role:'Q&A',          notes:'If health is good', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
    {id:'a10', name:'Traci Abramson',      status:'Confirmed', role:'Q&A',          notes:'', website:'', _expanded:false, infoForm:false, multiAuthor:false, swagSent:false, booksDonated:false, ticket:false, qrCode:false, signingConfirmed:false, thankYou:false},
  ],

  wishlist: [
    {name:'Alyse Haines',        note:''},
    {name:'Anne-Marie Meyer',    note:''},
    {name:'Anneka Walker',       note:''},
    {name:'Becky Momson',        note:''},
    {name:'Bridget E Baker',     note:'10k followers. Horse romantasy'},
    {name:'Courtney Walsh',      note:'Popular in her genre'},
    {name:'Deborah Hathaway',    note:''},
    {name:'Elaina Johnson',      note:''},
    {name:'Erica Penfold',       note:''},
    {name:'Heather Frost',       note:'Fantasy. Friends w Hill and Dana'},
    {name:'Jennifer Peel',       note:''},
    {name:'Kelly Davidson',      note:''},
    {name:'Kelly Orem',          note:''},
    {name:'Logan Piercy',        note:''},
    {name:'Marion de Ray',       note:'Contacted us on Insta'},
    {name:'Mellisa Lark',        note:''},
    {name:'Mimi Mathews',        note:''},
    {name:'Nancy Allan Campbell',note:'Love her'},
    {name:'Samantha Hastings',   note:'Contacted us on Insta. Romcom fall 2026'},
    {name:'Sarah Wilson',        note:''},
    {name:'Shannon Castleton',   note:'2027 goal!'},
    {name:'Tiffany Odekirk',     note:'Want to ask her'},
    {name:'Traci Abramson',      note:''},
  ],
};
